## File Input Linear Regression

In [16]:
import tensorflow as tf
import numpy as np

# np.loadtxt(파일경로, 구분자, 데이터형식)

data = np.loadtxt('./data/data-01-test-score.csv', delimiter=',', dtype=np.float32)

불러온 데이터를 확인  
column 1 ~ 3: train input  
column 4 : train output  

In [4]:
print(data)

[[ 73.  80.  75. 152.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [10]:
x_data = data[:, 0:-1]
y_data = data[:, [-1]]
print(x_data, "\n shape : ", x_data.shape)
print()
print(y_data, "\n shape : ", y_data.shape)

[[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 
 shape :  (25, 3)

[[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 
 shape :  (25, 1)


In [11]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=3, activation='linear'))
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 4         
Total params: 4
Trainable params: 4
Non-trainable params: 0
_________________________________________________________________


In [14]:
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))
train_history = tf.model.fit(x_data, y_data, epochs=2000)

Train on 25 samples
Epoch 1/2000
25/25 [==============================] - 1s 29ms/sample - loss: 34199.0898
Epoch 2/2000
25/25 [==============================] - 0s 239us/sample - loss: 12655.3115
Epoch 3/2000
25/25 [==============================] - 0s 239us/sample - loss: 4689.9761
Epoch 4/2000
25/25 [==============================] - 0s 160us/sample - loss: 1744.9667
Epoch 5/2000
25/25 [==============================] - 0s 120us/sample - loss: 656.1110
Epoch 6/2000
25/25 [==============================] - 0s 199us/sample - loss: 253.5269
Epoch 7/2000
25/25 [==============================] - 0s 80us/sample - loss: 104.6764
Epoch 8/2000
25/25 [==============================] - 0s 122us/sample - loss: 49.6381
Epoch 9/2000
25/25 [==============================] - 0s 153us/sample - loss: 29.2848
Epoch 10/2000
25/25 [==============================] - 0s 128us/sample - loss: 21.7557
Epoch 11/2000
25/25 [==============================] - 0s 228us/sample - loss: 18.9678
Epoch 12/2000
25/25 [

Epoch 95/2000
25/25 [==============================] - 0s 96us/sample - loss: 16.8086
Epoch 96/2000
25/25 [==============================] - 0s 80us/sample - loss: 16.8025
Epoch 97/2000
25/25 [==============================] - 0s 199us/sample - loss: 16.7964
Epoch 98/2000
25/25 [==============================] - 0s 200us/sample - loss: 16.7903
Epoch 99/2000
25/25 [==============================] - 0s 120us/sample - loss: 16.7842
Epoch 100/2000
25/25 [==============================] - 0s 279us/sample - loss: 16.7781
Epoch 101/2000
25/25 [==============================] - 0s 123us/sample - loss: 16.7720
Epoch 102/2000
25/25 [==============================] - 0s 279us/sample - loss: 16.7659
Epoch 103/2000
25/25 [==============================] - 0s 159us/sample - loss: 16.7598
Epoch 104/2000
25/25 [==============================] - 0s 282us/sample - loss: 16.7537
Epoch 105/2000
25/25 [==============================] - 0s 160us/sample - loss: 16.7476
Epoch 106/2000
25/25 [=================

Epoch 189/2000
25/25 [==============================] - 0s 119us/sample - loss: 16.2495
Epoch 190/2000
25/25 [==============================] - 0s 200us/sample - loss: 16.2437
Epoch 191/2000
25/25 [==============================] - 0s 199us/sample - loss: 16.2379
Epoch 192/2000
25/25 [==============================] - 0s 120us/sample - loss: 16.2321
Epoch 193/2000
25/25 [==============================] - 0s 159us/sample - loss: 16.2264
Epoch 194/2000
25/25 [==============================] - 0s 162us/sample - loss: 16.2206
Epoch 195/2000
25/25 [==============================] - 0s 240us/sample - loss: 16.2148
Epoch 196/2000
25/25 [==============================] - 0s 239us/sample - loss: 16.2091
Epoch 197/2000
25/25 [==============================] - 0s 117us/sample - loss: 16.2033
Epoch 198/2000
25/25 [==============================] - 0s 199us/sample - loss: 16.1976
Epoch 199/2000
25/25 [==============================] - 0s 121us/sample - loss: 16.1918
Epoch 200/2000
25/25 [==========

25/25 [==============================] - 0s 114us/sample - loss: 15.7268
Epoch 283/2000
25/25 [==============================] - 0s 279us/sample - loss: 15.7214
Epoch 284/2000
25/25 [==============================] - 0s 120us/sample - loss: 15.7159
Epoch 285/2000
25/25 [==============================] - 0s 160us/sample - loss: 15.7105
Epoch 286/2000
25/25 [==============================] - 0s 329us/sample - loss: 15.7050
Epoch 287/2000
25/25 [==============================] - 0s 80us/sample - loss: 15.6996
Epoch 288/2000
25/25 [==============================] - 0s 206us/sample - loss: 15.6941
Epoch 289/2000
25/25 [==============================] - 0s 120us/sample - loss: 15.6887
Epoch 290/2000
25/25 [==============================] - 0s 240us/sample - loss: 15.6832
Epoch 291/2000
25/25 [==============================] - 0s 120us/sample - loss: 15.6778
Epoch 292/2000
25/25 [==============================] - 0s 282us/sample - loss: 15.6724
Epoch 293/2000
25/25 [==========================

Epoch 376/2000
25/25 [==============================] - 0s 80us/sample - loss: 15.2277
Epoch 377/2000
25/25 [==============================] - 0s 69us/sample - loss: 15.2226
Epoch 378/2000
25/25 [==============================] - 0s 80us/sample - loss: 15.2174
Epoch 379/2000
25/25 [==============================] - 0s 80us/sample - loss: 15.2122
Epoch 380/2000
25/25 [==============================] - 0s 199us/sample - loss: 15.2071
Epoch 381/2000
25/25 [==============================] - 0s 78us/sample - loss: 15.2019
Epoch 382/2000
25/25 [==============================] - 0s 120us/sample - loss: 15.1968
Epoch 383/2000
25/25 [==============================] - 0s 121us/sample - loss: 15.1917
Epoch 384/2000
25/25 [==============================] - 0s 90us/sample - loss: 15.1865
Epoch 385/2000
25/25 [==============================] - 0s 159us/sample - loss: 15.1814
Epoch 386/2000
25/25 [==============================] - 0s 80us/sample - loss: 15.1763
Epoch 387/2000
25/25 [=================

Epoch 470/2000
25/25 [==============================] - 0s 148us/sample - loss: 14.7561
Epoch 471/2000
25/25 [==============================] - 0s 160us/sample - loss: 14.7512
Epoch 472/2000
25/25 [==============================] - 0s 210us/sample - loss: 14.7463
Epoch 473/2000
25/25 [==============================] - 0s 160us/sample - loss: 14.7415
Epoch 474/2000
25/25 [==============================] - 0s 120us/sample - loss: 14.7366
Epoch 475/2000
25/25 [==============================] - 0s 159us/sample - loss: 14.7317
Epoch 476/2000
25/25 [==============================] - 0s 160us/sample - loss: 14.7269
Epoch 477/2000
25/25 [==============================] - 0s 160us/sample - loss: 14.7220
Epoch 478/2000
25/25 [==============================] - 0s 120us/sample - loss: 14.7171
Epoch 479/2000
25/25 [==============================] - 0s 199us/sample - loss: 14.7123
Epoch 480/2000
25/25 [==============================] - 0s 200us/sample - loss: 14.7075
Epoch 481/2000
25/25 [==========

Epoch 564/2000
25/25 [==============================] - 0s 119us/sample - loss: 14.3103
Epoch 565/2000
25/25 [==============================] - 0s 256us/sample - loss: 14.3057
Epoch 566/2000
25/25 [==============================] - 0s 81us/sample - loss: 14.3011
Epoch 567/2000
25/25 [==============================] - 0s 120us/sample - loss: 14.2965
Epoch 568/2000
25/25 [==============================] - 0s 120us/sample - loss: 14.2919
Epoch 569/2000
25/25 [==============================] - 0s 128us/sample - loss: 14.2873
Epoch 570/2000
25/25 [==============================] - 0s 160us/sample - loss: 14.2827
Epoch 571/2000
25/25 [==============================] - 0s 121us/sample - loss: 14.2781
Epoch 572/2000
25/25 [==============================] - 0s 173us/sample - loss: 14.2735
Epoch 573/2000
25/25 [==============================] - 0s 119us/sample - loss: 14.2690
Epoch 574/2000
25/25 [==============================] - 0s 114us/sample - loss: 14.2644
Epoch 575/2000
25/25 [===========

Epoch 658/2000
25/25 [==============================] - 0s 161us/sample - loss: 13.8889
Epoch 659/2000
25/25 [==============================] - 0s 199us/sample - loss: 13.8846
Epoch 660/2000
25/25 [==============================] - 0s 105us/sample - loss: 13.8802
Epoch 661/2000
25/25 [==============================] - 0s 239us/sample - loss: 13.8759
Epoch 662/2000
25/25 [==============================] - 0s 120us/sample - loss: 13.8715
Epoch 663/2000
25/25 [==============================] - 0s 160us/sample - loss: 13.8672
Epoch 664/2000
25/25 [==============================] - 0s 120us/sample - loss: 13.8628
Epoch 665/2000
25/25 [==============================] - 0s 118us/sample - loss: 13.8585
Epoch 666/2000
25/25 [==============================] - 0s 120us/sample - loss: 13.8541
Epoch 667/2000
25/25 [==============================] - 0s 80us/sample - loss: 13.8498
Epoch 668/2000
25/25 [==============================] - 0s 120us/sample - loss: 13.8455
Epoch 669/2000
25/25 [===========

25/25 [==============================] - 0s 120us/sample - loss: 13.4946
Epoch 752/2000
25/25 [==============================] - 0s 160us/sample - loss: 13.4905
Epoch 753/2000
25/25 [==============================] - 0s 80us/sample - loss: 13.4863
Epoch 754/2000
25/25 [==============================] - 0s 107us/sample - loss: 13.4822
Epoch 755/2000
25/25 [==============================] - 0s 188us/sample - loss: 13.4781
Epoch 756/2000
25/25 [==============================] - 0s 80us/sample - loss: 13.4740
Epoch 757/2000
25/25 [==============================] - 0s 116us/sample - loss: 13.4699
Epoch 758/2000
25/25 [==============================] - 0s 120us/sample - loss: 13.4658
Epoch 759/2000
25/25 [==============================] - 0s 159us/sample - loss: 13.4617
Epoch 760/2000
25/25 [==============================] - 0s 120us/sample - loss: 13.4576
Epoch 761/2000
25/25 [==============================] - 0s 82us/sample - loss: 13.4535
Epoch 762/2000
25/25 [============================

Epoch 845/2000
25/25 [==============================] - 0s 199us/sample - loss: 13.1175
Epoch 846/2000
25/25 [==============================] - 0s 80us/sample - loss: 13.1136
Epoch 847/2000
25/25 [==============================] - 0s 200us/sample - loss: 13.1097
Epoch 848/2000
25/25 [==============================] - 0s 120us/sample - loss: 13.1058
Epoch 849/2000
25/25 [==============================] - 0s 120us/sample - loss: 13.1019
Epoch 850/2000
25/25 [==============================] - 0s 120us/sample - loss: 13.0980
Epoch 851/2000
25/25 [==============================] - 0s 121us/sample - loss: 13.0941
Epoch 852/2000
25/25 [==============================] - 0s 163us/sample - loss: 13.0902
Epoch 853/2000
25/25 [==============================] - 0s 120us/sample - loss: 13.0863
Epoch 854/2000
25/25 [==============================] - 0s 121us/sample - loss: 13.0824
Epoch 855/2000
25/25 [==============================] - 0s 80us/sample - loss: 13.0786
Epoch 856/2000
25/25 [============

Epoch 939/2000
25/25 [==============================] - 0s 120us/sample - loss: 12.7607
Epoch 940/2000
25/25 [==============================] - 0s 152us/sample - loss: 12.7570
Epoch 941/2000
25/25 [==============================] - 0s 80us/sample - loss: 12.7533
Epoch 942/2000
25/25 [==============================] - 0s 107us/sample - loss: 12.7497
Epoch 943/2000
25/25 [==============================] - 0s 119us/sample - loss: 12.7460
Epoch 944/2000
25/25 [==============================] - 0s 99us/sample - loss: 12.7423
Epoch 945/2000
25/25 [==============================] - 0s 160us/sample - loss: 12.7386
Epoch 946/2000
25/25 [==============================] - 0s 110us/sample - loss: 12.7349
Epoch 947/2000
25/25 [==============================] - 0s 120us/sample - loss: 12.7313
Epoch 948/2000
25/25 [==============================] - 0s 638us/sample - loss: 12.7276
Epoch 949/2000
25/25 [==============================] - 0s 121us/sample - loss: 12.7239
Epoch 950/2000
25/25 [============

Epoch 1032/2000
25/25 [==============================] - 0s 129us/sample - loss: 12.4266
Epoch 1033/2000
25/25 [==============================] - 0s 120us/sample - loss: 12.4231
Epoch 1034/2000
25/25 [==============================] - 0s 125us/sample - loss: 12.4196
Epoch 1035/2000
25/25 [==============================] - 0s 120us/sample - loss: 12.4161
Epoch 1036/2000
25/25 [==============================] - 0s 120us/sample - loss: 12.4126
Epoch 1037/2000
25/25 [==============================] - 0s 117us/sample - loss: 12.4091
Epoch 1038/2000
25/25 [==============================] - 0s 121us/sample - loss: 12.4057
Epoch 1039/2000
25/25 [==============================] - 0s 163us/sample - loss: 12.4022
Epoch 1040/2000
25/25 [==============================] - 0s 120us/sample - loss: 12.3987
Epoch 1041/2000
25/25 [==============================] - 0s 157us/sample - loss: 12.3952
Epoch 1042/2000
25/25 [==============================] - 0s 160us/sample - loss: 12.3917
Epoch 1043/2000
25/25

Epoch 1125/2000
25/25 [==============================] - 0s 106us/sample - loss: 12.1102
Epoch 1126/2000
25/25 [==============================] - 0s 120us/sample - loss: 12.1069
Epoch 1127/2000
25/25 [==============================] - 0s 159us/sample - loss: 12.1036
Epoch 1128/2000
25/25 [==============================] - 0s 161us/sample - loss: 12.1003
Epoch 1129/2000
25/25 [==============================] - 0s 176us/sample - loss: 12.0969
Epoch 1130/2000
25/25 [==============================] - 0s 120us/sample - loss: 12.0936
Epoch 1131/2000
25/25 [==============================] - 0s 120us/sample - loss: 12.0903
Epoch 1132/2000
25/25 [==============================] - 0s 80us/sample - loss: 12.0871
Epoch 1133/2000
25/25 [==============================] - 0s 119us/sample - loss: 12.0837
Epoch 1134/2000
25/25 [==============================] - 0s 80us/sample - loss: 12.0804
Epoch 1135/2000
25/25 [==============================] - 0s 159us/sample - loss: 12.0772
Epoch 1136/2000
25/25 [

25/25 [==============================] - 0s 207us/sample - loss: 11.8136
Epoch 1218/2000
25/25 [==============================] - 0s 120us/sample - loss: 11.8105
Epoch 1219/2000
25/25 [==============================] - 0s 160us/sample - loss: 11.8073
Epoch 1220/2000
25/25 [==============================] - 0s 160us/sample - loss: 11.8042
Epoch 1221/2000
25/25 [==============================] - 0s 160us/sample - loss: 11.8010
Epoch 1222/2000
25/25 [==============================] - 0s 232us/sample - loss: 11.7979
Epoch 1223/2000
25/25 [==============================] - 0s 160us/sample - loss: 11.7948
Epoch 1224/2000
25/25 [==============================] - 0s 230us/sample - loss: 11.7916
Epoch 1225/2000
25/25 [==============================] - 0s 109us/sample - loss: 11.7885
Epoch 1226/2000
25/25 [==============================] - 0s 120us/sample - loss: 11.7854
Epoch 1227/2000
25/25 [==============================] - 0s 160us/sample - loss: 11.7823
Epoch 1228/2000
25/25 [==============

Epoch 1310/2000
25/25 [==============================] - 0s 112us/sample - loss: 11.5294
Epoch 1311/2000
25/25 [==============================] - 0s 239us/sample - loss: 11.5264
Epoch 1312/2000
25/25 [==============================] - 0s 121us/sample - loss: 11.5235
Epoch 1313/2000
25/25 [==============================] - 0s 120us/sample - loss: 11.5205
Epoch 1314/2000
25/25 [==============================] - 0s 162us/sample - loss: 11.5175
Epoch 1315/2000
25/25 [==============================] - 0s 160us/sample - loss: 11.5146
Epoch 1316/2000
25/25 [==============================] - 0s 200us/sample - loss: 11.5116
Epoch 1317/2000
25/25 [==============================] - 0s 120us/sample - loss: 11.5087
Epoch 1318/2000
25/25 [==============================] - 0s 120us/sample - loss: 11.5057
Epoch 1319/2000
25/25 [==============================] - 0s 279us/sample - loss: 11.5027
Epoch 1320/2000
25/25 [==============================] - 0s 194us/sample - loss: 11.4998
Epoch 1321/2000
25/25

Epoch 1403/2000
25/25 [==============================] - 0s 160us/sample - loss: 11.2601
Epoch 1404/2000
25/25 [==============================] - 0s 125us/sample - loss: 11.2573
Epoch 1405/2000
25/25 [==============================] - 0s 80us/sample - loss: 11.2545
Epoch 1406/2000
25/25 [==============================] - 0s 200us/sample - loss: 11.2517
Epoch 1407/2000
25/25 [==============================] - 0s 80us/sample - loss: 11.2489
Epoch 1408/2000
25/25 [==============================] - 0s 80us/sample - loss: 11.2461
Epoch 1409/2000
25/25 [==============================] - 0s 150us/sample - loss: 11.2433
Epoch 1410/2000
25/25 [==============================] - 0s 279us/sample - loss: 11.2405
Epoch 1411/2000
25/25 [==============================] - 0s 121us/sample - loss: 11.2377
Epoch 1412/2000
25/25 [==============================] - 0s 239us/sample - loss: 11.2348
Epoch 1413/2000
25/25 [==============================] - 0s 120us/sample - loss: 11.2320
Epoch 1414/2000
25/25 [=

Epoch 1496/2000
25/25 [==============================] - 0s 162us/sample - loss: 11.0049
Epoch 1497/2000
25/25 [==============================] - 0s 117us/sample - loss: 11.0022
Epoch 1498/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.9996
Epoch 1499/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.9969
Epoch 1500/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.9942
Epoch 1501/2000
25/25 [==============================] - 0s 199us/sample - loss: 10.9915
Epoch 1502/2000
25/25 [==============================] - 0s 128us/sample - loss: 10.9889
Epoch 1503/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.9862
Epoch 1504/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.9836
Epoch 1505/2000
25/25 [==============================] - 0s 123us/sample - loss: 10.9809
Epoch 1506/2000
25/25 [==============================] - 0s 119us/sample - loss: 10.9782
Epoch 1507/2000
25/25

Epoch 1589/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.7629
Epoch 1590/2000
25/25 [==============================] - 0s 122us/sample - loss: 10.7604
Epoch 1591/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.7578
Epoch 1592/2000
25/25 [==============================] - 0s 189us/sample - loss: 10.7553
Epoch 1593/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.7528
Epoch 1594/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.7503
Epoch 1595/2000
25/25 [==============================] - 0s 111us/sample - loss: 10.7477
Epoch 1596/2000
25/25 [==============================] - 0s 164us/sample - loss: 10.7452
Epoch 1597/2000
25/25 [==============================] - 0s 199us/sample - loss: 10.7427
Epoch 1598/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.7401
Epoch 1599/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.7377
Epoch 1600/2000
25/25

25/25 [==============================] - 0s 120us/sample - loss: 10.5358
Epoch 1682/2000
25/25 [==============================] - 0s 159us/sample - loss: 10.5334
Epoch 1683/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.5310
Epoch 1684/2000
25/25 [==============================] - 0s 159us/sample - loss: 10.5286
Epoch 1685/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.5262
Epoch 1686/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.5238
Epoch 1687/2000
25/25 [==============================] - 0s 200us/sample - loss: 10.5214
Epoch 1688/2000
25/25 [==============================] - 0s 159us/sample - loss: 10.5191
Epoch 1689/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.5167
Epoch 1690/2000
25/25 [==============================] - 0s 199us/sample - loss: 10.5142
Epoch 1691/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.5119
Epoch 1692/2000
25/25 [==============

Epoch 1774/2000
25/25 [==============================] - 0s 199us/sample - loss: 10.3181
Epoch 1775/2000
25/25 [==============================] - 0s 199us/sample - loss: 10.3158
Epoch 1776/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.3135
Epoch 1777/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.3112
Epoch 1778/2000
25/25 [==============================] - 0s 160us/sample - loss: 10.3090
Epoch 1779/2000
25/25 [==============================] - 0s 194us/sample - loss: 10.3067
Epoch 1780/2000
25/25 [==============================] - 0s 119us/sample - loss: 10.3044
Epoch 1781/2000
25/25 [==============================] - 0s 81us/sample - loss: 10.3021
Epoch 1782/2000
25/25 [==============================] - 0s 112us/sample - loss: 10.2999
Epoch 1783/2000
25/25 [==============================] - 0s 80us/sample - loss: 10.2976
Epoch 1784/2000
25/25 [==============================] - 0s 77us/sample - loss: 10.2953
Epoch 1785/2000
25/25 [=

Epoch 1867/2000
25/25 [==============================] - 0s 158us/sample - loss: 10.1115
Epoch 1868/2000
25/25 [==============================] - 0s 80us/sample - loss: 10.1093
Epoch 1869/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.1072
Epoch 1870/2000
25/25 [==============================] - 0s 202us/sample - loss: 10.1050
Epoch 1871/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.1029
Epoch 1872/2000
25/25 [==============================] - 0s 130us/sample - loss: 10.1007
Epoch 1873/2000
25/25 [==============================] - 0s 153us/sample - loss: 10.0985
Epoch 1874/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.0964
Epoch 1875/2000
25/25 [==============================] - 0s 120us/sample - loss: 10.0942
Epoch 1876/2000
25/25 [==============================] - 0s 319us/sample - loss: 10.0921
Epoch 1877/2000
25/25 [==============================] - 0s 111us/sample - loss: 10.0899
Epoch 1878/2000
25/25 

Epoch 1960/2000
25/25 [==============================] - 0s 165us/sample - loss: 9.9155
Epoch 1961/2000
25/25 [==============================] - 0s 80us/sample - loss: 9.9135
Epoch 1962/2000
25/25 [==============================] - 0s 80us/sample - loss: 9.9114
Epoch 1963/2000
25/25 [==============================] - 0s 80us/sample - loss: 9.9094
Epoch 1964/2000
25/25 [==============================] - 0s 80us/sample - loss: 9.9073
Epoch 1965/2000
25/25 [==============================] - 0s 119us/sample - loss: 9.9053
Epoch 1966/2000
25/25 [==============================] - 0s 117us/sample - loss: 9.9032
Epoch 1967/2000
25/25 [==============================] - 0s 107us/sample - loss: 9.9012
Epoch 1968/2000
25/25 [==============================] - 0s 120us/sample - loss: 9.8991
Epoch 1969/2000
25/25 [==============================] - 0s 129us/sample - loss: 9.8971
Epoch 1970/2000
25/25 [==============================] - 0s 120us/sample - loss: 9.8950
Epoch 1971/2000
25/25 [=============

학습한 모델로 점수 예측

In [15]:
print("Your score will be ", tf.model.predict([[100, 70, 101]]))
print("Other scores will be ", tf.model.predict([[60, 70, 110], [90, 100, 80]]))

Your score will be  [[191.28087]]
Other scores will be  [[167.37576]
 [177.53223]]
