## Softmax Classifier

In [1]:
import tensorflow as tf
import numpy as np

x_raw = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_raw = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

x_data = np.array(x_raw, dtype=np.float32)
y_data = np.array(y_raw, dtype=np.float32)

tf.keras.layers.Dense Args:
* units : 양의 정수, output space 의 dimensionailty 를 정의
* activation : 사용할 activation function. 기본값 : 'linear'
* use_bias : Boolean 값. 해당 layer 가 bias vector를 사용할 지 여부를 나타냄
* input_dim : input vector의 dimension

In [3]:
classes = 3

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(input_dim=4, units=classes, use_bias=True))

activation function으로 softmax를 이용

In [4]:
tf.model.add(tf.keras.layers.Activation('softmax'))

In [5]:
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1),
                metrics=['accuracy'])
tf.model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 3)                 15        
_________________________________________________________________
activation (Activation)      (None, 3)                 0         
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [8]:
train_history = tf.model.fit(x_data, y_data, epochs=200)

Train on 8 samples
Epoch 1/200
8/8 [==============================] - 1s 112ms/sample - loss: 1.9445 - accuracy: 0.3750
Epoch 2/200
8/8 [==============================] - 0s 873us/sample - loss: 1.4004 - accuracy: 0.3750
Epoch 3/200
8/8 [==============================] - 0s 873us/sample - loss: 1.3627 - accuracy: 0.2500
Epoch 4/200
8/8 [==============================] - 0s 873us/sample - loss: 1.3499 - accuracy: 0.3750
Epoch 5/200
8/8 [==============================] - 0s 624us/sample - loss: 1.4100 - accuracy: 0.3750
Epoch 6/200
8/8 [==============================] - 0s 876us/sample - loss: 1.3795 - accuracy: 0.3750
Epoch 7/200
8/8 [==============================] - 0s 1000us/sample - loss: 1.3829 - accuracy: 0.2500
Epoch 8/200
8/8 [==============================] - 0s 748us/sample - loss: 1.3476 - accuracy: 0.3750
Epoch 9/200
8/8 [==============================] - 0s 872us/sample - loss: 1.2969 - accuracy: 0.3750
Epoch 10/200
8/8 [==============================] - 0s 1ms/sample - los

Epoch 82/200
8/8 [==============================] - 0s 748us/sample - loss: 0.7686 - accuracy: 0.7500
Epoch 83/200
8/8 [==============================] - 0s 748us/sample - loss: 0.7122 - accuracy: 0.6250
Epoch 84/200
8/8 [==============================] - 0s 993us/sample - loss: 0.7649 - accuracy: 0.7500
Epoch 85/200
8/8 [==============================] - 0s 1ms/sample - loss: 0.7084 - accuracy: 0.6250
Epoch 86/200
8/8 [==============================] - 0s 748us/sample - loss: 0.7613 - accuracy: 0.7500
Epoch 87/200
8/8 [==============================] - 0s 871us/sample - loss: 0.7048 - accuracy: 0.6250
Epoch 88/200
8/8 [==============================] - 0s 748us/sample - loss: 0.7579 - accuracy: 0.6250
Epoch 89/200
8/8 [==============================] - 0s 997us/sample - loss: 0.7012 - accuracy: 0.6250
Epoch 90/200
8/8 [==============================] - 0s 1ms/sample - loss: 0.7546 - accuracy: 0.6250
Epoch 91/200
8/8 [==============================] - 0s 374us/sample - loss: 0.6978 - a

Epoch 162/200
8/8 [==============================] - 0s 873us/sample - loss: 0.6757 - accuracy: 0.6250
Epoch 163/200
8/8 [==============================] - 0s 497us/sample - loss: 0.6154 - accuracy: 0.6250
Epoch 164/200
8/8 [==============================] - 0s 748us/sample - loss: 0.6741 - accuracy: 0.6250
Epoch 165/200
8/8 [==============================] - 0s 624us/sample - loss: 0.6138 - accuracy: 0.6250
Epoch 166/200
8/8 [==============================] - 0s 623us/sample - loss: 0.6725 - accuracy: 0.6250
Epoch 167/200
8/8 [==============================] - 0s 623us/sample - loss: 0.6121 - accuracy: 0.6250
Epoch 168/200
8/8 [==============================] - 0s 623us/sample - loss: 0.6710 - accuracy: 0.6250
Epoch 169/200
8/8 [==============================] - 0s 498us/sample - loss: 0.6105 - accuracy: 0.6250
Epoch 170/200
8/8 [==============================] - 0s 623us/sample - loss: 0.6694 - accuracy: 0.6250
Epoch 171/200
8/8 [==============================] - 0s 499us/sample - lo

In [13]:
a = tf.model.predict(np.array([[1,11,7,9]]))
print(a, tf.keras.backend.eval(tf.argmax(a, axis=1)))

b = tf.model.predict(np.array([[1,3,4,3]]))
print(b, tf.keras.backend.eval(tf.argmax(b, axis=1)))

c = tf.model.predict(np.array([[1,1,0,1]]))
c_onehot = tf.model.predict_classes(np.array([[1,1,0,1]]))
print(c, c_onehot)

abc = tf.model.predict(np.array([[1,11,7,9], [1,3,4,3], [1,1,0,1]]))
abc_onehot = tf.model.predict_classes(np.array([[1,11,7,9], [1,3,4,3], [1,1,0,1]]))
print(abc_onehot)

[[0.4139371  0.58501476 0.00104815]] [1]
[[0.192981   0.5979778  0.20904124]] [1]
[[0.01551721 0.09752895 0.88695383]] [2]
[1 1 2]
