## Softmax Zoo Classifier

1. 해당 데이터셋을 불러온 후 training feature 와 output으로 나누어줌

In [1]:
import tensorflow as tf
import numpy as np

data = np.loadtxt('./data/data-04-zoo.csv', delimiter=',', dtype=np.float32)
print(data)

x_data = data[:, 0: -1]
y_data = data[:, [-1]]

print()

print(x_data.shape, y_data.shape)

[[1. 0. 0. ... 0. 1. 0.]
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 3.]
 ...
 [1. 0. 0. ... 0. 1. 0.]
 [0. 0. 1. ... 0. 0. 6.]
 [0. 1. 1. ... 0. 0. 1.]]

(101, 16) (101, 1)


2. 분류 type 이 0 ~ 6 으로 7개, input feature 수가 16개 임을 파악하였으므로 모델을 작성한다

In [2]:
classes = 7

y_onehot = tf.keras.utils.to_categorical(y_data, classes)
# class vector 들을 binary class matrix 로 변환

print("one hot : \n", y_onehot)

one hot : 
 [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0.

In [3]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=classes, input_dim = 16, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy',
                 optimizer=tf.keras.optimizers.SGD(lr=0.01), metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 7)                 119       
Total params: 119
Trainable params: 119
Non-trainable params: 0
_________________________________________________________________


3. 모델을 학습시키고 임의의 데이터로 평가해본다

In [4]:
train_history = tf.model.fit(x_data, y_onehot, epochs=500)

Train on 101 samples
Epoch 1/500
101/101 [==============================] - 1s 7ms/sample - loss: 2.7542 - accuracy: 0.2178
Epoch 2/500
101/101 [==============================] - 0s 138us/sample - loss: 2.5525 - accuracy: 0.2178
Epoch 3/500
101/101 [==============================] - 0s 178us/sample - loss: 2.3656 - accuracy: 0.2178
Epoch 4/500
101/101 [==============================] - 0s 197us/sample - loss: 2.1870 - accuracy: 0.2277
Epoch 5/500
101/101 [==============================] - 0s 177us/sample - loss: 2.0420 - accuracy: 0.2376
Epoch 6/500
101/101 [==============================] - 0s 188us/sample - loss: 1.9029 - accuracy: 0.2970
Epoch 7/500
101/101 [==============================] - 0s 178us/sample - loss: 1.7881 - accuracy: 0.2871
Epoch 8/500
101/101 [==============================] - 0s 203us/sample - loss: 1.6997 - accuracy: 0.4455
Epoch 9/500
101/101 [==============================] - 0s 188us/sample - loss: 1.6149 - accuracy: 0.5545
Epoch 10/500
101/101 [==============

101/101 [==============================] - 0s 178us/sample - loss: 0.8204 - accuracy: 0.8218
Epoch 78/500
101/101 [==============================] - 0s 148us/sample - loss: 0.8158 - accuracy: 0.8218
Epoch 79/500
101/101 [==============================] - ETA: 0s - loss: 0.8120 - accuracy: 0.87 - 0s 178us/sample - loss: 0.8107 - accuracy: 0.8218
Epoch 80/500
101/101 [==============================] - 0s 158us/sample - loss: 0.8068 - accuracy: 0.8218
Epoch 81/500
101/101 [==============================] - 0s 158us/sample - loss: 0.8012 - accuracy: 0.8218
Epoch 82/500
101/101 [==============================] - 0s 197us/sample - loss: 0.7977 - accuracy: 0.8218
Epoch 83/500
101/101 [==============================] - 0s 207us/sample - loss: 0.7936 - accuracy: 0.8218
Epoch 84/500
101/101 [==============================] - 0s 208us/sample - loss: 0.7896 - accuracy: 0.8020
Epoch 85/500
101/101 [==============================] - 0s 217us/sample - loss: 0.7856 - accuracy: 0.8020
Epoch 86/500
101/

Epoch 153/500
101/101 [==============================] - 0s 277us/sample - loss: 0.6043 - accuracy: 0.8515
Epoch 154/500
101/101 [==============================] - 0s 227us/sample - loss: 0.6023 - accuracy: 0.8614
Epoch 155/500
101/101 [==============================] - 0s 188us/sample - loss: 0.6006 - accuracy: 0.8416
Epoch 156/500
101/101 [==============================] - 0s 217us/sample - loss: 0.5983 - accuracy: 0.8614
Epoch 157/500
101/101 [==============================] - 0s 178us/sample - loss: 0.5967 - accuracy: 0.8416
Epoch 158/500
101/101 [==============================] - 0s 197us/sample - loss: 0.5950 - accuracy: 0.8614
Epoch 159/500
101/101 [==============================] - 0s 267us/sample - loss: 0.5930 - accuracy: 0.8416
Epoch 160/500
101/101 [==============================] - 0s 355us/sample - loss: 0.5918 - accuracy: 0.8416
Epoch 161/500
101/101 [==============================] - 0s 336us/sample - loss: 0.5899 - accuracy: 0.8416
Epoch 162/500
101/101 [==============

101/101 [==============================] - 0s 168us/sample - loss: 0.4950 - accuracy: 0.8614
Epoch 230/500
101/101 [==============================] - 0s 158us/sample - loss: 0.4945 - accuracy: 0.8614
Epoch 231/500
101/101 [==============================] - 0s 188us/sample - loss: 0.4931 - accuracy: 0.8614
Epoch 232/500
101/101 [==============================] - 0s 168us/sample - loss: 0.4919 - accuracy: 0.8614
Epoch 233/500
101/101 [==============================] - 0s 158us/sample - loss: 0.4906 - accuracy: 0.8614
Epoch 234/500
101/101 [==============================] - 0s 178us/sample - loss: 0.4900 - accuracy: 0.8614
Epoch 235/500
101/101 [==============================] - 0s 148us/sample - loss: 0.4888 - accuracy: 0.8614
Epoch 236/500
101/101 [==============================] - 0s 148us/sample - loss: 0.4875 - accuracy: 0.8614
Epoch 237/500
101/101 [==============================] - 0s 138us/sample - loss: 0.4866 - accuracy: 0.8614
Epoch 238/500
101/101 [============================

101/101 [==============================] - 0s 188us/sample - loss: 0.4279 - accuracy: 0.8812
Epoch 305/500
101/101 [==============================] - 0s 227us/sample - loss: 0.4269 - accuracy: 0.8812
Epoch 306/500
101/101 [==============================] - 0s 187us/sample - loss: 0.4258 - accuracy: 0.8812
Epoch 307/500
101/101 [==============================] - 0s 197us/sample - loss: 0.4251 - accuracy: 0.8812
Epoch 308/500
101/101 [==============================] - 0s 227us/sample - loss: 0.4239 - accuracy: 0.8812
Epoch 309/500
101/101 [==============================] - 0s 207us/sample - loss: 0.4233 - accuracy: 0.8812
Epoch 310/500
101/101 [==============================] - 0s 217us/sample - loss: 0.4229 - accuracy: 0.8812
Epoch 311/500
101/101 [==============================] - 0s 188us/sample - loss: 0.4219 - accuracy: 0.8812
Epoch 312/500
101/101 [==============================] - 0s 148us/sample - loss: 0.4211 - accuracy: 0.8812
Epoch 313/500
101/101 [============================

101/101 [==============================] - 0s 148us/sample - loss: 0.3786 - accuracy: 0.9109
Epoch 381/500
101/101 [==============================] - 0s 217us/sample - loss: 0.3780 - accuracy: 0.9307
Epoch 382/500
101/101 [==============================] - 0s 217us/sample - loss: 0.3773 - accuracy: 0.9307
Epoch 383/500
101/101 [==============================] - 0s 227us/sample - loss: 0.3767 - accuracy: 0.9208
Epoch 384/500
101/101 [==============================] - 0s 178us/sample - loss: 0.3761 - accuracy: 0.9307
Epoch 385/500
101/101 [==============================] - 0s 178us/sample - loss: 0.3754 - accuracy: 0.9307
Epoch 386/500
101/101 [==============================] - 0s 168us/sample - loss: 0.3746 - accuracy: 0.9307
Epoch 387/500
101/101 [==============================] - 0s 188us/sample - loss: 0.3743 - accuracy: 0.9307
Epoch 388/500
101/101 [==============================] - ETA: 0s - loss: 0.4200 - accuracy: 0.90 - 0s 168us/sample - loss: 0.3739 - accuracy: 0.9307
Epoch 389

101/101 [==============================] - 0s 207us/sample - loss: 0.3403 - accuracy: 0.9307
Epoch 456/500
101/101 [==============================] - 0s 247us/sample - loss: 0.3399 - accuracy: 0.9307
Epoch 457/500
101/101 [==============================] - 0s 217us/sample - loss: 0.3397 - accuracy: 0.9307
Epoch 458/500
101/101 [==============================] - 0s 227us/sample - loss: 0.3392 - accuracy: 0.9307
Epoch 459/500
101/101 [==============================] - 0s 247us/sample - loss: 0.3387 - accuracy: 0.9307
Epoch 460/500
101/101 [==============================] - 0s 247us/sample - loss: 0.3382 - accuracy: 0.9307
Epoch 461/500
101/101 [==============================] - 0s 247us/sample - loss: 0.3376 - accuracy: 0.9307
Epoch 462/500
101/101 [==============================] - 0s 207us/sample - loss: 0.3371 - accuracy: 0.9307
Epoch 463/500
101/101 [==============================] - 0s 198us/sample - loss: 0.3369 - accuracy: 0.9307
Epoch 464/500
101/101 [============================

In [5]:
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]])
# expected prediction == 3 (feathers)

print(tf.model.predict(test_data), tf.model.predict_classes(test_data))

[[0.03064605 0.04233878 0.06655006 0.8215294  0.02164223 0.00156527
  0.01572822]] [3]


4. 모든 training input 에 대하여 잘 분류가 되었는지 확인해 본다.

In [6]:
pred = tf.model.predict_classes(x_data)
idx = 1
for p, y in zip(pred, y_data.flatten()): # y 데이터를 1차원으로 변환 후 zip 을 이용하여 pair를 만들어줌
    print("[#{}] [{}] Prediction : {} Real : {}".format(idx, p == int(y), p, int(y)))
    idx += 1

[#1] [True] Prediction : 0 Real : 0
[#2] [True] Prediction : 0 Real : 0
[#3] [True] Prediction : 3 Real : 3
[#4] [True] Prediction : 0 Real : 0
[#5] [True] Prediction : 0 Real : 0
[#6] [True] Prediction : 0 Real : 0
[#7] [True] Prediction : 0 Real : 0
[#8] [True] Prediction : 3 Real : 3
[#9] [True] Prediction : 3 Real : 3
[#10] [True] Prediction : 0 Real : 0
[#11] [True] Prediction : 0 Real : 0
[#12] [True] Prediction : 1 Real : 1
[#13] [True] Prediction : 3 Real : 3
[#14] [True] Prediction : 6 Real : 6
[#15] [True] Prediction : 6 Real : 6
[#16] [True] Prediction : 6 Real : 6
[#17] [True] Prediction : 1 Real : 1
[#18] [True] Prediction : 0 Real : 0
[#19] [True] Prediction : 3 Real : 3
[#20] [True] Prediction : 0 Real : 0
[#21] [True] Prediction : 1 Real : 1
[#22] [True] Prediction : 1 Real : 1
[#23] [True] Prediction : 0 Real : 0
[#24] [True] Prediction : 1 Real : 1
[#25] [True] Prediction : 5 Real : 5
[#26] [True] Prediction : 4 Real : 4
[#27] [True] Prediction : 4 Real : 4
[#28] [Tru