## data_preprocessing(scaling)

In [1]:
import tensorflow as tf
import numpy as np


1. 0~1 사이의 값들로 데이터를 전처리해주는 함수를 정의

In [2]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise를 추가해줌으로써 0으로 나누는 경우를 방지해준다
    return numerator / (denominator + 1e-7)


2. 스케일링이 필요한 데이터 셋(데이터 간의 값의 차이가 큼)

In [3]:
data = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

3. min_max_scaler 함수를 이용하여 데이터를 0과 1사이의 값으로 scaling

In [4]:
data = min_max_scaler(data) # 이 전처리 과정을 거치지 않으면 학습이 제대로 되지 않음.
print(data)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [5]:
x_data = data[:, 0:-1]
y_data = data[:, [-1]]

tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=1e-5))

tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 1)                 5         
_________________________________________________________________
activation (Activation)      (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [6]:
train_history = tf.model.fit(x_data, y_data, epochs=200)

Train on 8 samples
Epoch 1/200
8/8 [==============================] - 1s 83ms/sample - loss: 2.6611
Epoch 2/200
8/8 [==============================] - 0s 500us/sample - loss: 2.6609
Epoch 3/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6607
Epoch 4/200
8/8 [==============================] - 0s 567us/sample - loss: 2.6605
Epoch 5/200
8/8 [==============================] - 0s 499us/sample - loss: 2.6604
Epoch 6/200
8/8 [==============================] - 0s 748us/sample - loss: 2.6602
Epoch 7/200
8/8 [==============================] - 0s 500us/sample - loss: 2.6600
Epoch 8/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6598
Epoch 9/200
8/8 [==============================] - 0s 499us/sample - loss: 2.6596
Epoch 10/200
8/8 [==============================] - 0s 748us/sample - loss: 2.6594
Epoch 11/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6592
Epoch 12/200
8/8 [==============================] - 0s 374us/sample - loss: 2.

Epoch 100/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6420
Epoch 101/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6418
Epoch 102/200
8/8 [==============================] - 0s 500us/sample - loss: 2.6416
Epoch 103/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6414
Epoch 104/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6412
Epoch 105/200
8/8 [==============================] - 0s 388us/sample - loss: 2.6410
Epoch 106/200
8/8 [==============================] - 0s 249us/sample - loss: 2.6408
Epoch 107/200
8/8 [==============================] - 0s 480us/sample - loss: 2.6406
Epoch 108/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6404
Epoch 109/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6403
Epoch 110/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6401
Epoch 111/200
8/8 [==============================] - 0s 374us/sample - loss:

Epoch 198/200
8/8 [==============================] - 0s 372us/sample - loss: 2.6232
Epoch 199/200
8/8 [==============================] - 0s 348us/sample - loss: 2.6230
Epoch 200/200
8/8 [==============================] - 0s 374us/sample - loss: 2.6228


In [7]:
pred = tf.model.predict(x_data)
score = tf.model.evaluate(x_data, y_data)

print("Prediction : \n", pred)
print("Cost : ", score)

8/8 [==============================] - 0s 15ms/sample - loss: 2.6226
Prediction : 
 [[-1.3847641 ]
 [-1.6768863 ]
 [-1.1992354 ]
 [-0.63128555]
 [-0.9810933 ]
 [-0.89873725]
 [-0.3854628 ]
 [-0.35415637]]
Cost :  2.622608184814453
